name = "grilme99/playfab_luau"
version = "0.1.0"
license = "MIT"
private = true

workspace_memebrs = ["common/"]

[target]
environment = "roblox"

[indices]
default = "https://github.com/daimond113/pesde-index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
Jest = { wally = "jsdotlua/jest", version = "^3.10.0" }
JestGlobals = { wally = "jsdotlua/jest-globals", version = "^3.10.0" }
