/// <reference path="PlayFab.d.ts" />
/// <reference path="PlayFabAdmin.d.ts" />
/// <reference path="PlayFabClient.d.ts" />
/// <reference path="PlayFabMatchmaker.d.ts" />
/// <reference path="PlayFabServer.d.ts" />
/// <reference path="PlayFabAuthentication.d.ts" />
/// <reference path="PlayFabCloudScript.d.ts" />
/// <reference path="PlayFabData.d.ts" />
/// <reference path="PlayFabEvents.d.ts" />
/// <reference path="PlayFabExperimentation.d.ts" />
/// <reference path="PlayFabInsights.d.ts" />
/// <reference path="PlayFabGroups.d.ts" />
/// <reference path="PlayFabLocalization.d.ts" />
/// <reference path="PlayFabMultiplayer.d.ts" />
/// <reference path="PlayFabProfiles.d.ts" />
 
export const Settings: PlayFabModule.IPlayFabSettings
export const PlayFabAdmin: PlayFabAdminModule.IPlayFabAdmin
export const PlayFabClient: PlayFabClientModule.IPlayFabClient
export const PlayFabMatchmaker: PlayFabMatchmakerModule.IPlayFabMatchmaker
export const PlayFabServer: PlayFabServerModule.IPlayFabServer
export const PlayFabAuthentication: PlayFabAuthenticationModule.IPlayFabAuthentication
export const PlayFabCloudScript: PlayFabCloudScriptModule.IPlayFabCloudScript
export const PlayFabData: PlayFabDataModule.IPlayFabData
export const PlayFabEvents: PlayFabEventsModule.IPlayFabEvents
export const PlayFabExperimentation: PlayFabExperimentationModule.IPlayFabExperimentation
export const PlayFabInsights: PlayFabInsightsModule.IPlayFabInsights
export const PlayFabGroups: PlayFabGroupsModule.IPlayFabGroups
export const PlayFabLocalization: PlayFabLocalizationModule.IPlayFabLocalization
export const PlayFabMultiplayer: PlayFabMultiplayerModule.IPlayFabMultiplayer
export const PlayFabProfiles: PlayFabProfilesModule.IPlayFabProfiles
