name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          cache: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        shell: bash
        run: sh bin/install-packages.sh

      - name: Analyze
        shell: bash
        run: sh bin/analyze.sh

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          cache: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: selene modules/ common/ .lune/

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          cache: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check style
        run: stylua --check modules/

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          cache: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        shell: bash
        run: sh bin/install-packages.sh

      - name: Run tests
        shell: bash
        run: lune run test --ci
        env:
          ROBLOX_OC_API_KEY: ${{ secrets.ROBLOX_OC_API_KEY }}
          CI: true
